Controllers/AccountController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FieldGroove_Views.Controllers
{
    public class AccountController : Controller
    {
       public ActionResult Login()
        {
            return View();
        }
        public ActionResult Signup()
        {
            return View();
        }
    
    }
}

Controllers/EstimateController.cs
using Microsoft.AspNetCore.Mvc;

namespace FieldGroove_Views.Controllers
{
    public class EstimateController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Test()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace FieldGroove_Views.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Opportunity()
        {
            return View();
        }   

        public IActionResult Dashboard()
        {
            return View();
        }  public IActionResult LeadConvert()
        {
            return View();
        }
    }
}

Controllers/LeadsController.cs
using Microsoft.AspNetCore.Mvc;

namespace FieldGroove_Views.Controllers
{
    public class LeadsController : Controller
    {
        public IActionResult LeadsCreation()
        {
            return View();
        }
    }
}   

Controllers/SideBarpagesController.cs
using Microsoft.AspNetCore.Mvc;

namespace FieldGroove_Views.Controllers
{
    public class SideBarpagesController : Controller
    {
        public IActionResult Settings()
        {
            return View();
        }

		public IActionResult Calendar()
        {
            return View();
        }
        public IActionResult Task()
        {
            return View();
        }
        public IActionResult CustomerManagement()
        {
            return View();
        }
        public IActionResult Users()
        {
            return View();
        }

        public IActionResult AddCustomer()
        {
            return View();
        }
	}
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace FieldGroove_Views.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Home/Dashboard.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row p-0 m-0">
    <div class="col-8 border">
        <div class="d-flex justify-content-between p-3">
            <div>
                <h3>Dashboard</h3>
            </div>
            <div>
                <button type="button" class="btn btn-success">Start New Opportunity</button>
                <button type="button" class="btn btn-success" onclick="window.location.href='@Url.Action("LeadsCreation", "Leads")' ;">
                    Add New Lead
                </button>
            </div>
        </div>
        <img src="~/Images/pngwing.com.png" class="imagedash" alt="sf" />


    </div>
<div class="col-4">
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FieldGroove_Views</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FieldGroove_Views.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" />
    <script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/PapaParse/5.3.0/papaparse.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
</head>

<style>
    ::-webkit-scrollbar {
        display: none;
    }

</style>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-1 p-0 bg-light d-lg-block d-none">

                <ul class="nav nav-pills nav-flush flex-column mb-auto text-center">
                    <li class="nav-item bg-primary">
                        <a href="#" onclick="window.location.href = '@Url.Action("Dashboard", "Home")';" class="nav-link py-3 border-bottom rounded-0" aria-current="page" data-bs-toggle="tooltip" data-bs-placement="right" aria-label="Home" data-bs-original-title="Home">
                            <img src="~/Images/output-onlinepngtools.png" class="header-logo" alt="sf" />
                        </a>
                    </li>
                    <li>
                        <a asp-controller="SideBarPages" asp-action="Task" class="nav-link py-2 rounded-0" data-bs-toggle="tooltip" data-bs-placement="right" aria-label="Dashboard" data-bs-original-title="Dashboard">
                            <i class="bi bi-check2-square" style="font-size: 2.5rem; color:dimgray"></i><br />
                            <label style="color:dimgray">Tasks</label>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="SideBarPages" asp-action="Calendar" class="nav-link py-2  rounded-0" data-bs-toggle="tooltip" data-bs-placement="right" aria-label="Orders" data-bs-original-title="Orders">
                            <i class="bi bi-calendar3" style="font-size: 2.5rem; color:dimgray"></i><br />
                            <label style="color:dimgray">Calandar</label>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link py-2 rounded-0" data-bs-toggle="tooltip" data-bs-placement="right" aria-label="Products" data-bs-original-title="Products">
                            <i class="bi bi-graph-up" style="font-size: 2.5rem; color:dimgray"></i><br />
                            <label style="color:dimgray">Reports</label>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="SideBarPages" asp-action="Users" class="nav-link py-2 rounded-0" data-bs-toggle="tooltip" data-bs-placement="right" aria-label="Customers" data-bs-original-title="Customers">
                            <i class="bi bi-people" style="font-size: 2.5rem; color:dimgray"></i><br />
                            <label style="color:dimgray">Users</label>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="SideBarPages" asp-action="Settings" class="nav-link py-2  rounded-0" data-bs-toggle="tooltip" data-bs-placement="right" aria-label="Customers" data-bs-original-title="Customers">
                            <i class="bi bi-gear-fill" style="font-size: 2.5rem; color:dimgray"></i><br />
                            <label style="color:dimgray">Settings</label>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link py-2 rounded-0" data-bs-toggle="tooltip" data-bs-placement="right" aria-label="Customers" data-bs-original-title="Customers">
                            <i class="bi bi-question-circle" style="font-size: 2.5rem; color:dimgray"></i><br />
                            <label style="color:dimgray">Support</label>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link py-2 rounded-0" data-bs-toggle="tooltip" data-bs-placement="right" aria-label="Customers" data-bs-original-title="Customers">
                            <i class="bi bi-speedometer2" style="font-size: 2.5rem; color:dimgray"></i><br />
                            <label style="color:dimgray">Super Admin</label>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-11 col-12 p-0">
                <nav class="navbar navbar-expand-lg bg-primary text-white">
                    <div class="container-fluid">
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="nav-link active text-white" aria-current="page" asp-controller="Home" asp-action="Index">Leads</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active text-white" aria-current="page" asp-controller="Home" asp-action="Opportunity">Opportunities </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active text-white" asp-controller="Estimate" asp-action="Index">Jobs</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Accounting
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" href="#">Action</a></li> 
                                        <li><a class="dropdown-item" href="#">Another action</a></li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-white" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Coustmers
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a asp-controller="SideBarPages" asp-action="CustomerManagement" class="dropdown-item">Customer Management</a></li>
                                        <li><a class="dropdown-item" href="#">Contacts</a></li>                                       
                                    </ul>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Inventory
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" href="#">Action</a></li>
                                        <li><a class="dropdown-item" href="#">Another action</a></li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Dispatcher
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" href="#">Action</a></li>
                                        <li><a class="dropdown-item" href="#">Another action</a></li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                                    </ul>
                                </li>
                            </ul>
                            <div class="d-flex align-items-center ">
                                <form class="d-flex align-items-center gap-2" role="search">
                                    <div class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle text-white  d-flex flex-row-reverse align-items-center" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            ABINGTON
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" href="#">Action</a></li>
                                            <li><a class="dropdown-item" href="#">Another action</a></li>
                                            <li><hr class="dropdown-divider"></li>
                                            <li><a class="dropdown-item text-white" href="#">Something else here</a></li>
                                        </ul>
                                    </div>
                                    <input class="form-control me-2 rounded-pill" type="search" placeholder="Search" aria-label="Search">
                                    <div class="d-flex align-items-center gap-2">
                                        <iconify-icon icon="mdi:bell-outline" style="font-size: 2rem;"></iconify-icon>
                                        <iconify-icon icon="carbon:user-avatar" style="font-size: 2rem;"></iconify-icon>
                                        <h6 class="text-nowrap mb-0">Vijay Kishor</h6>
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </nav>
             <div class="">
                    @RenderBody()
             </div>
            </div>

        </div>

    </div>
</body>


</html>

Views/SideBarPages/Calendar.cshtml
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='utf-8' />
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.11/main.min.css' />
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.11/index.global.min.js'></script>
    <script src='https://code.jquery.com/jquery-3.6.4.min.js'></script>
    <style>
        .fc-title {
            text-align: center;
        }
    </style>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var calendarEl = document.getElementById('calendar');
            $.ajax({
                url: 'https://localhost:44367/api/Calendar/GetCalendarEvents',
                method: 'GET',
                success: function (response) {
                    console.log("Calendar Response:", response);
                    var events = response.map(function (event) {
                        console.log("Title:", event.Title);
                        console.log("Notes:", event.Notes);
                        return {
                            title: event.Title,
                            start: event.StartTime,
                            end: event.EndTime,
                            color: 'primary',
                            textColor: 'white'
                        };
                    });
                    var calendar = new FullCalendar.Calendar(calendarEl, {
                        initialView: 'dayGridMonth',
                        events: events,
                        eventContent: function (arg) {
                            return {
                                html: '<div class="fc-title">' + arg.event.title + '</div>'
                            };
                        }
                    });

                    calendar.render();
                },
                error: function () {
                    alert('Failed to load events!');
                }
            });
        });

    </script>
</head>
<body>
    <div id='calendar' class="p-3"></div>
</body>
</html>

Views/SideBarPages/CustomerManagement.cshtml
<div class="row">
    <div class="col-8 border-end">
        <div class="border-bottom p-2">
            <table class="table-bordered border-secondary-subtle w-100">
                <tr>
                    <td class="p-1"><input class="form-control" placeholder="Search customers..." type="text" /></td>
                    <td class="p-1">
                        <select class="form-select" aria-label="Default select example">
                            <option selected>Open this select menu</option>
                            <option value="1">One</option>
                            <option value="2">Two</option>
                            <option value="3">Three</option>
                        </select>
                    </td>
                    <td class="p-1">
                        <select class="form-select" aria-label="Default select example">
                            <option selected>Open this select menu</option>
                            <option value="1">One</option>
                            <option value="2">Two</option>
                            <option value="3">Three</option>
                        </select>
                    </td>
                    <td class="p-1"><input type="checkbox" />Include Inactive</td>
                    <td class="p-1"><button type="button" class="btn btn-primary">Filter</button></td>
                </tr>
            </table>
        </div>
        <div class="d-flex justify-content-between border-bottom py-3 px-2 m-0">
            <div>
                <h3>Customers</h3>
            </div>
            <div>
                <button type="button" class="btn btn-success" onclick="window.location.href='@Url.Action("AddCustomer", "SideBarpages")' ;">Add Customer</button>
            </div>
        </div>
        <div class="row mt-3">
            <table id="leadsTable" class="table table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Salesperson</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-4">

    </div>
</div>

<script>
    $(document).ready(function () {
        var dataTable = $('#leadsTable').DataTable({
            columns: [
                { data: 'FirstName', defaultContent: '-' },
                { data: 'Phone', defaultContent: '-' },
                { data: 'Email', defaultContent: '-' },
                { data: 'Salesman', defaultContent: '-' }

            ]
        });
        $(document).on('click', '.save-task-btn', function () {
            saveTask();
        });
        function loadAllData() {
            $.ajax({
                url: 'https://localhost:44367/api/Customers/cust',
                method: 'GET',
                dataType: 'json',
                success: function (data) {
                    dataTable.clear();
                    dataTable.rows.add(data).draw();
                },
                error: function (error) {
                    console.error('Error fetching data:', error);
                }
            });
        }
        loadAllData();
        $('input[type="search"]').on('keyup', function () {
            dataTable.search($(this).val()).draw();
        });

    });
</script>

Views/SideBarPages/Users.cshtml
<div class="row">
    <div class="col-8 border-end py-0 m-0">
        <div class="d-flex justify-content-between p-3 border-bottom">
            <div>
                <h3>Users</h3>
            </div>
            <div class="d-flex gap-2">
                <div class="dropdown">
                    <button class="btn btn-transparent bg-transparent border-0 dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        View
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </div>
                <button class="btn btn-success" onclick="window.location.href='@Url.Action("Index", "User")' ;">Add User</button>
            </div>
        </div>
        <div class="row mt-2">
            <table id="leadsTable" class="table table-hover table-sm">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Location</th>
                        <th>Username</th>
                        <th>Roles</th>                       
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-4">

    </div>
</div>

<script>
    $(document).ready(function () {
        var dataTable = $('#leadsTable').DataTable({
            columns: [
                { data: 'FirstName', defaultContent: '-' },
                { data: 'LocationId', defaultContent: '-' },
                { data: 'Username', defaultContent: '-' },
                { data: '   ', defaultContent: '-' }            

            ]
        });
        $(document).on('click', '.save-task-btn', function () {
            saveTask();
        });
        function loadAllData() {
            $.ajax({
                url: 'https://localhost:44367/api/user/user',
                method: 'GET',
                dataType: 'json',
                success: function (data) {
                    dataTable.clear();
                    dataTable.rows.add(data).draw();
                },
                error: function (error) {
                    console.error('Error fetching data:', error);
                }
            });
        }
        loadAllData();
        $('input[type="search"]').on('keyup', function () {
            dataTable.search($(this).val()).draw();
        });

    });
</script>